name: CommitLint Check

on: [push, pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install commitlint and dependencies
        run: |
          npm install commitlint@latest @commitlint/config-conventional

      - name: Get the first commit hash (for exclusion)
        id: get_first_commit
        run: |
          FIRST_COMMIT_HASH=$(git rev-list --max-parents=0 HEAD)
          echo "FIRST_COMMIT_HASH=$FIRST_COMMIT_HASH" >> $GITHUB_ENV

      - name: Validate current commit (push event)
        if: github.event_name == 'push'
        run: |
          LAST_COMMIT_HASH=$(git rev-parse HEAD)
          if [ "$LAST_COMMIT_HASH" != "$FIRST_COMMIT_HASH" ]; then
            npx commitlint --last --verbose
          else
            echo "Skipping commitlint for the first commit"
          fi

      - name: Validate all commits in pull request
        if: github.event_name == 'pull_request'
        run: |
          COMMITS=$(git log --format=%H ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
          for COMMIT in $COMMITS; do
            if [ "$COMMIT" != "$FIRST_COMMIT_HASH" ]; then
              npx commitlint --from $COMMIT --to $COMMIT --verbose
            else
              echo "Skipping commitlint for the first commit"
            fi
          done
